### ISSUE TITLE
TBS校验失败

### ISSUE THREAD

**Issue by Peter-Duan** [Aruelius/tieba_sign#17]
这是报错信息

> 扫描成功,请在手机端确认登录!
确认登陆成功
Login: True

>//这是我print的rsp
{'error': {'errno': 320022, 'errmsg': '', 'usermsg': 'TBS校验失败'}, 'server_time': 3427, 'time': 1588880764, 'ctime': 0, 'logid': 2764429882, 'error_code': '0'}
Exception in thread Thread-1:

>Traceback (most recent call last):
  File "tieba_sign.py", line 264, in sign
    if rsp['user_info']['is_sign_in'] == 1:
KeyError: 'user_info'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "tieba_sign.py", line 267, in sign
    if rsp['error_msg'] == 'need vcode': # 这里也不清楚手机端需不需要验证码
KeyError: 'error_msg'

>+------+------+
| 贴吧 | 状态 |
+------+------+
+------+------+
总共签到1个贴吧,耗时:34秒
`

**Comment by Aruelius** [comment]
还能复现么，我测试没有问题的。
