### ISSUE TITLE
我这个也有问题，不知道咋回事。如以下：

### ISSUE THREAD

**Issue by Aaron-leo** [Aruelius/tieba_sign#20]
注意：请使用IE浏览器打开二维码链接！！！
扫描成功,请在手机端确认登录!
确认登陆成功
Traceback (most recent call last):
  File "tieba_sign.py", line 316, in <module>
    tieba.main()
  File "tieba_sign.py", line 301, in main
    self.login(user)
  File "tieba_sign.py", line 159, in login
    self.qr_login(user)
  File "tieba_sign.py", line 153, in qr_login
    self.qr_login_set_cookie(bduss)
  File "tieba_sign.py", line 98, in qr_login_set_cookie
    rsp = json.loads(r.text.replace("'",'"'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 1158 (char 1157)

**Comment by Aruelius** [comment]
"tieba_sign.py" 文件的 98 行，上面加上一行：
`print(r.text)`
